contrastAndAspectError: Don't grab focus for plotting
This commit replaces three instances of using

    figure(handle)

in a loop with the corresponding

    set(0, 'CurrentFigure', handle)

This avoids 'figure's annoying side effect of grabbing window focus
which is especially pronounced when the example is being run from
start to finish without interactive pause.